pmm_user:
    resource: "@PMMUserBundle/Resources/config/routing.yml"
    prefix:   /

pmm_labo:
    resource: "@PMMLaboBundle/Resources/config/routing.yml"
    prefix:   /

pmm_core:
    resource: "@PMMCoreBundle/Resources/config/routing.yml"
    prefix:   /
    
login:
    path: /login
    defaults:
        _controller: PMMUserBundle:Security:login
        
login_check:
    path: /login_check
        
logout:
    path: /logout
    
home:
    path:     /
    defaults: { _controller: "PMMCoreBundle:Commande:index" }
    methods:  GET
