commande_index:
    path:     /
    defaults: { _controller: "PMMCoreBundle:Commande:index" }
    methods:  GET

commande_show:
    path:     /{id}/show
    defaults: { _controller: "PMMCoreBundle:Commande:show" }
    methods:  GET

commande_new:
    path:     /new
    defaults: { _controller: "PMMCoreBundle:Commande:new" }
    methods:  [GET, POST]

commande_edit:
    path:     /{id}/edit
    defaults: { _controller: "PMMCoreBundle:Commande:edit" }
    methods:  [GET, POST]

commande_delete:
    path:     /{id}/delete
    defaults: { _controller: "PMMCoreBundle:Commande:delete" }
    methods:  DELETE
    
commande_print:
    path:     /{id}/print
    defaults: { _controller: "PMMCoreBundle:Commande:print" }
    methods:  [GET, POST]
    
commande_pdf:
    path:     /{id}/pdf
    defaults: { _controller: "PMMCoreBundle:Print:commande" }
    methods:  [GET, POST]
    
commande_custum-new:
    path:     /{id}/new
    defaults: { _controller: "PMMCoreBundle:Commande:custumNew" }
    methods:  [GET, POST]
    
commande_etat:
    path:     /etat
    defaults: { _controller: "PMMCoreBundle:Commande:etat" }
    methods:  GET
    
commande_etat2:
    path:     /etat2/{d1}/{m1}/{y1}/{d2}/{m2}/{y2}
    defaults: { _controller: "PMMCoreBundle:Commande:etat2" }
    methods:  GET
    
commande_global:
    path:     /etatglobal
    defaults: { _controller: "PMMCoreBundle:Commande:etatglobal" }
    methods:  GET
