commande_index:
    path:     /
    defaults: { _controller: "PMMCoreBundle:Commande:index" }
    methods:  GET

commande_show:
    path:     /{id}/show
    defaults: { _controller: "PMMCoreBundle:Commande:show" }
    methods:  GET

commande_new:
    path:     /new
    defaults: { _controller: "PMMCoreBundle:Commande:new" }
    methods:  [GET, POST]

commande_edit:
    path:     /{id}/edit
    defaults: { _controller: "PMMCoreBundle:Commande:edit" }
    methods:  [GET, POST]

commande_delete:
    path:     /{id}/delete
    defaults: { _controller: "PMMCoreBundle:Commande:delete" }
    methods:  DELETE
    
commande_print:
    path:     /{id}/print
    defaults: { _controller: "PMMCoreBundle:Commande:print" }
    methods:  [GET, POST]
    
commande_custum-new:
    path:     /{id}/new
    defaults: { _controller: "PMMCoreBundle:Commande:custumNew" }
    methods:  [GET, POST]
