pmm_core_patient:
    resource: "@PMMCoreBundle/Resources/config/routing/patient.yml"
    prefix:   /patient
    
pmm_core_medicament:
    resource: "@PMMCoreBundle/Resources/config/routing/medicament.yml"
    prefix:   /medicament
    
pmm_core_commande:
    resource: "@PMMCoreBundle/Resources/config/routing/commande.yml"
    prefix:   /commande
    
pmm_core_medoc1:
    resource: "@PMMCoreBundle/Resources/config/routing/medoc1.yml"
    prefix:   /medoc1

pmm_core_medoc2:
    resource: "@PMMCoreBundle/Resources/config/routing/medoc2.yml"
    prefix:   /medoc2
    
pmm_core_medoc3:
    resource: "@PMMCoreBundle/Resources/config/routing/medoc3.yml"
    prefix:   /medoc3
