services:
    pmm_core.amount_commande:
        class: PMM\CoreBundle\AmountCommande\AmountCommande
        tags:
            - { name: doctrine.event_listener, event: postPersist}
            - { name: doctrine.event_listener, event: postUpdate}
    #pmm_core.save_com_medoc:
        #class: PMM\CoreBundle\SaveComMedoc\SaveComMedoc
        #tags:
            #- { name: doctrine.event_listener, event: postPersist}
